var oddstory = []
oddstory[0] = "Once upon a time, there was a cat named Pearl that was known to play 24/7. He was born in a house where he was sly indeed, and lived most of his days in this place called east london which was located in the land of England. One dark evening Pearl being known as the sly cat which he clearly was, ran so fast that he entered into Ireland. He spent a couple of years there working his way to buy a ticket home. He later went back to the old house where not a single soul believed what happened to Pearl.";

oddstory[1] = "Once upon a time, there was a dog named Goofy that was known to bark 24/7. He was born in a mountain where he was loud indeed, and lived most of his days in this place called New Milford which was located in the land of USA. One big evening Goofy being known as the loud dog which he clearly was, barked so retarded that he entered into Thailand. He spent a couple of years there working his way to buy a ticket home. He later went back to the old mountain where not a single soul believed what happened to Goofy.";

oddstory[2] = "Once upon a time, there was a giraffe named Russell that was known to graze 24/7. He was born in a safari where he was tall indeed, and lived most of his days in this place called National Kenyan Reserve which was located in the land of Africa. One almighty evening Russell being known as the tall Giraffe which he clearly was, grazed so high that he entered into the Moon. He spent a couple of years there working his way to buy a ticket home. He later went back to the old safari where not a single soul believed what happened to Russell.";

oddstory[3] = "Once upon a time, there was a rat named Slippa that was known to roam 24/7. He was born in a subway station where he was comfortable indeed, and lived most of his days in this place called Brooklyn which was located in the land of USA. One rainy evening Slippa being known as the comfortable rat which he clearly was, ran so fast that he entered into Queens. He spent a couple of years there working his way to buy a ticket home. He later went back to the old subway station where not a single soul believed what happened to Slippa.";

oddstory[4] = "Once upon a time, there was a Tiger named Sher-Khan that was known to snore 24/7. He was born in a jungle where he was lazy indeed, and lived most of his days in this place called Sherwoods which was located in the land of India. One late evening Sher-Khan being known as the lazy tiger which he clearly was, walked so sleepy that he entered into The Pride Lands. He spent a couple of years there working his way to buy a ticket home. He later went back to the old Sherwoods where not a single soul believed what happened to Sher-Khan.";

oddstory[5] = "Once upon a time, there was a lion named Simba that was known to growl 24/7. He was born in a forest where he was explorative indeed, and lived most of his days in this place called Pride Lands which was located in the land of Africa. One mysterious evening Simba being known as the explorative lion which he clearly was, fled so far that he entered into Asia. He spent a couple of years there working his way to buy a ticket home. He later went back to the old forest where not a single soul believed what happened to Simba.";

oddstory[6] = "Once upon a time, there was a bird named Pidgey that was known to chirp 24/7. He was born in a tree where he was melodic indeed, and lived most of his days in this place called Godawari which was located in the land of Nepal. One dim evening Pidgey being known as the melodic bird which he clearly was, sang so sharp that he entered into the woods. He spent a couple of years there working his way to buy a ticket home. He later went back to the old PLACE where not a single soul believed what happened to Pidgey.";

oddstory[7] = "Once upon a time, there was a fish named Magikarp that was known to splash 24/7. He was born in a sea where he was jittery indeed, and lived most of his days in this place called C-Town which was located in the land of Kanto. One magical evening Magikarp being known as the jittery fish which he clearly was, splashed so hard that he entered into Jhoto. He spent a couple of years there working his way to buy a ticket home. He later went back to the old sea where not a single soul believed what happened to Magikarp.";

function oddStories() {
    var randomStory = Math.floor(Math.random()*(oddstory.length));
    document.getElementById('pstory').innerHTML = oddstory[randomStory];
}